export class LocalUI {
  static icons = {
    // color
    projects: 'projects:svg:local',
    // other
    market: 'market:svg:local',
    sprints: 'sprints:svg:local:stroked',
    terms: 'terms:svg:local:stroked',
    modules: 'modules:svg:local:stroked',
    model: 'model:svg:local:stroked',
    entities: 'entities:svg:local:stroked',
    enums: 'enums:svg:local:stroked',
    features: 'features:svg:local:stroked',
    validate: 'validate:svg:local:stroked',
    general: 'general:svg:local:stroked',
    graphQl: 'graphql:svg:local',
    rest: 'rest:svg:local',
    story: 'story:svg:local',
    resources: 'resources:svg:local',
    issues: 'issues:svg:local',
    print: 'print:svg:local:stroked',
    public: 'public:svg:local:stroked',
    project: 'project:svg:local:stroked',
    free: 'free:svg:local:stroked',
    startup: 'startup:svg:local:stroked',
    enterprise: 'enterprise:svg:local:stroked',
    featureOn: 'feature-on:svg:local:stroked',
    featureOff: 'feature-off:svg:local:stroked',
    agreement: 'agreement:svg:local:stroked',
    policy: 'policy:svg:local:stroked',
    security: 'security:svg:local:stroked',
    contacts: 'contacts:svg:local:stroked',
    support: 'support:svg:local:stroked',
    cp: 'cloud_payments:svg:local',
    quote: 'quote:svg:local:stroked',
  };
}
